
Scatterplots (“scatterplots.html”)  :  
This interactive scatter plot visualization, created using Altair, explores the relationships between "Exam_Score" and various numerical variables—Hours_Studied, Attendance, Previous_Scores, Tutoring_Sessions, and Sleep_Hours—within the "StudentPerformanceFactors" dataset. By incorporating a selection interval along the x-axis, the visualization not only highlights correlations between exam scores and these metrics but also allows for dynamic comparison of how these variables interact with one another across specific ranges. Key takeaways include a clear positive correlation between exam scores and both hours studied and attendance, indicating that increased study time and class presence tend to boost performance. In contrast, exam scores and previous scores show only a slight positive correlation, suggesting little consistent influence, while sleep hours exhibit no strong correlation with exam scores, implying minimal impact on performance. Interestingly, students with the highest exam scores tend to have fewer tutoring sessions, possibly indicating self-sufficiency or diminishing returns from additional support.

Bar charts (“supportDistributions.html”) : 
This visualization comprises three side-by-side bar charts, each depicting the distribution of "Exam_Score" for subsets of students filtered by a categorical variable—Teacher_Quality, Access_to_Resources, and Parental_Involvement—representing levels of support and resources available to students. Each chart is paired with an interactive dropdown menu, allowing users to select a specific category (Low, Medium, High) and view the corresponding exam score distribution. Key takeaways reveal distinct patterns: low parental involvement skews left with lower scores, medium involvement shows slightly better scores, and high involvement skews right with even higher scores, suggesting a positive link between parental support and academic performance. For access to resources, medium access yields more students with higher scores than low access, while high access boasts the highest mean exam score, indicating that resource availability enhances outcomes. Teacher quality shows less variation—low and medium quality distributions are similar in average, but high quality skews right, suggesting a modest benefit in score distribution despite a comparable mean to medium quality. Together, these interactive charts highlight how varying levels of support influence exam score distributions, with parental involvement and resource access showing clearer impacts than teacher quality.

Bound Bar and Scatter (“ScoreAndMotivation.html”) :
This data visualization features a scatterplot and a linked bar chart to explore the relationship between hours studied, exam scores, and student motivation levels within the "StudentPerformanceFactors" dataset. The scatterplot plots "Hours_Studied" on the x-axis against "Exam_Score" on the y-axis, with each point colored by motivation level (e.g., Low, Medium, High), revealing a positive correlation between study time and exam performance at a glance. However, the intermixed colors suggest no clear relationship between motivation level and exam score, a pattern confirmed by the even distribution of motivation levels among the highest exam scores. The bar chart below, dynamically bound to a selection interval on the scatterplot, displays the count of students by motivation level for the selected data points. For the lowest exam scores, low motivation dominates, though high and medium levels are nearly equal, indicating some influence of motivation at the lower end. Among students who studied the most hours, motivation levels are evenly split, while those who studied the least show a majority with medium motivation, with high and low levels equally represented. This visualization highlights that while hours studied strongly predict exam scores, motivation’s impact is less consistent, varying subtly across different study and performance ranges.
